version: "3"

services:
    kafka:
        image: "bitnami/kafka:latest"
        networks:
            - awesomecoder
        environment:
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        environment:
            -NODE_ENV: ${NODE_ENV:-development}
        working_dir: /app
        # entrypoint: /app/entrypoint.sh
        command: ["node", "app.js"]
        networks:
            - awesomecoder

networks:
    awesomecoder:
        driver: bridge
